fluidRow(
  column(12,
         HTML(
           "<strong> <font size = '6'> Welcome to PodIdentApp ! </font> </strong> <br> 
         This app helps you to visualise, explore and compare podocyte data from different studies <br>
         <br>
         Datasets used in this app are : <br>
<strong> Single-Cell Transcriptome Profiling of the Kidney Glomerulus Identifies Key Cell Types and Reactions to Injury (Chung) : </strong> <br>
Single-cell transcriptome of the glomerulus in healthy and injured-model mice.
Single-cell RNA sequencing was performed on glomeruli from healthy mice and from four different disease models, nephrotoxic serum nephritis, diabetes, doxorubicin toxicity, and CD2AP deficiency. C57BL/6J and BTBR ob/ob (BTBR.Cg-Lepob/WiscJ) mice were used. Single-cell data were processed and further analyzed by Partek Flow software (version 8.0.19.0707).<br>
<br>

<strong> A Single-Cell Transcriptome Atlas of the Mouse Glomerulus (Karaiskos) : </strong> <br>
Single-cell transcriptome of the glomerulus in WT mice. Single-cell suspensions of glomeruli were collected from 8-week-old wild-type CD1 male mice. Highly parallel single-cell transcriptome profiling was generated by Drop-seq. Single-cell data were analyzed with Drop-seq tools v. 1.124, dropbead and Seurat. <br>
<br>

<strong> Single-cell transcriptomics of the mouse kidney reveals potential cellular targets of kidney disease (Park) : </strong> <br>
Single-cell transcriptome of the kidney in healthy mice.
Droplet-based single-cell RNA sequencing was performed on whole kidney from seven healthy male C57BL/6 mice. Single-cell data were processed and analyzed by Seurat and edgeR. <br>
<br>

<strong> Molecular fingerprinting of the podocyte reveals novel gene and protein regulatory networks (Boerries transcriptome) : </strong> <br>
The transcriptome of mouse podocytes.
Transcriptomic profiling of podocytes and non-podocytes were generated by Affymetrix WT Mouse Gene ST 1.0. miRNA expression profiling was acquired through ArrayStar. Podocytes and non-podocytes were isolated by FACS sorting. Gt(ROSA)26Sortm4(ACTB-tdTomato,-EGFP)Luo/J x hNPHS2Cre mice were used. Statistical analysis of transcriptomic and miRNA data was performed with R. <br>
<br>

<strong> Genome-Wide Analysis of Wilms' Tumor 1-Controlled Gene Expression in Podocytes Reveals Key Regulatory Mechanisms (Kann) : </strong> <br>
The transcriptome of mouse podocytes.
CHIP-seq data were acquired from pooled samples of 6 CD-1 wild-type mice using an anti-WT1 (Wilm's tumor suppressor 1) antibody. GFP labeled podocytes from Nphs2-Cre and R26-mTmG hybrid mice were isolated by FACS and were subject to RNA sequencing. Data were mapped through Eland and Bowtie. <br>
<br>

<strong> A Multi-layered Quantitative In Vivo Expression Atlas of the Podocyte Unravels Kidney Disease Candidate Genes (Rinschen and Goeddel) : </strong> <br>
The proteome and transcriptome of podocytes and non-podocyte cells in native mouse glomeruli.
Podocytes and non-podocyte fractions were isolated from glomeruli by FACS sorting. Pod.Cre x mT/mG mice were used. Podocyte and non-podocyte fractions were subjected to label-free quantitative proteomics analysis. Quantification was done via MaxQuant. <br>
<br>

<strong> Molecular fingerprinting of the podocyte reveals novel gene and protein regulatory networks (Boerries proteome) : </strong> <br>
The proteome of mouse podocytes.
Podocytes and non-podocytes were isolated by FACS sorting. Gt(ROSA)26Sortm4(ACTB-tdTomato,-EGFP)Luo/J x hNPHS2Cre mice were used. Podocytes and non-podocytes were subjected to SILAC and label-free proteomic quantification. Proteomic data were processed by MaxQuant. <br>
<br>

<strong> Tripartite Separation of Glomerular Cell Types and Proteomes from Reporter-Free Mice (CMS) : </strong> <br>
The proteome of podocytes, mesangial cells and glomerular endothelial cells in mice of three strains.
Murine mesangial, endothelial cells and podocytes were isolated by timMEP. C57BL/6, BALB/c and mT/mD mice were used. Proteomic data were searched by MaxQuant and quantified by LFQ algorithm. <br>
<br>
<br>

<font size = +1> <strong>
More info about the app can be found on <a href = https://github.com/LenaBonin73/PodIdentApp> https://github.com/LenaBonin73/PodIdentApp </a> </strong> </font> <br>
<br>")
  )
  
)